<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
<fieldset>
  <legend>Please select one of the following</legend>
  <input type="radio" name="action" id="en cours" value="en cours" /><label for="en cours">en cours</label><br />
  <input type="radio" name="action" id="terminee" value="terminee"  /><label for="terminee">terminee</label><br />
  <input type="radio" name="action" id="en attente" value="en attente" /><label for="en attente">en attente</label><br />
</fieldset>

</body>
</html>